name: update-lives1-list

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 21:00 UTC 触发
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 步骤 1：拉取代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史记录

      # 步骤 2：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用 Python 3.9

      # 步骤 3：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests futures

      # 步骤 4：运行 Python 脚本
      - name: Run iptv
        run: python iptv.py

      # 步骤 4.5：调试输出
      - name: Debug
        run: |
          echo "当前目录内容："
          ls -la
          echo "ls.txt 内容："
          cat ls.txt || echo "ls.txt 不存在"
          echo "zszby.txt 内容："
          cat zszby.txt || echo "zszby.txt 不存在"

      # 步骤 5：提交生成的文件
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 进行推送
        run: |
          git config --global user.email "362213335lkh@gmail.com"
          git config --global user.name "l19270149853"
          
          # 检查文件是否存在
          if [ -f "ls.txt" ] && [ -f "zszby.txt" ]; then
            git add ls.txt zszby.txt  # 只提交生成的文件
            if git diff --cached --quiet; then
              echo "没有文件变更，无需提交。"
            else
              git commit -m "自动更新 IPTV 列表 [skip ci]"
              git pull --rebase  # 同步远程分支
              git push origin main  # 推送到 main 分支
            fi
          else
            echo "文件 ls.txt 或 zszby.txt 不存在，跳过提交。"
          fi
