name: tv1

on:
  schedule:
    - cron: '0 21 * * *'  # 每天 21:00 UTC 触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests futures

      - name: Run tv1
        run: python tv1.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "362213335lkh@gmail.com"
          git config --global user.name "l19270149853"
          git add tv1.txt  # 关键添加
          git commit -m "自动更新 IPTV 列表 [skip ci]"
          git pull --rebase
          git push origin main
